name: Go

on:
  push:
    branches: [ "workflows", "main" ]
    paths-ignore:
        - '**/README.md'
  pull_request:
    branches: [ "workflows", "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: "1.20"

    - name: Checkout
      uses: actions/checkout@v3

    - name: Test
      run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...
      env:
        GOFLAGS: "-mod=vendor"

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
